java_binary(
    name = "AstPrinter",
    srcs = ["AstPrinter.java"],
    main_class = "org.javacomp.tool.AstPrinter",
    deps = [
        "//external:guava",
        "//external:javac",
        "//src/main/java/org/javacomp/parser",
    ],
)
