package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "io",
    srcs = glob(["*.java"]),
    deps = [
        "//external:guava",
        "//src/main/java/org/javacomp/logging",
    ],
)
