package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "reference",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/org/javacomp/logging",
        "//src/main/java/org/javacomp/model",
        "//src/main/java/org/javacomp/parser",
        "//src/main/java/org/javacomp/typesolver",
        "//third_party:auto_value",
        "//third_party:guava",
        "//third_party:javac",
    ],
)
