java_library(
    name = "storage",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/org/javacomp/model",
        "//src/main/java/org/javacomp/typesolver",
        "//third_party:flogger",
        "//third_party:gson",
        "//third_party:guava",
        "//third_party:jsr305",
    ],
)
