java_library(
    name = "symbol_index_scope",
    srcs = ["SymbolIndexScope.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//external:guava",
        "//external:jsr305",
        "//src/main/proto:symbol_proto",
    ],
)
