package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "model",
    srcs = glob(["*.java"]),
    deps = [
        "//external:guava",
        "//external:jsr305",
    ],
)
