package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "model",
    srcs = glob(["*.java"]),
    deps = [
        "//external:guava",
        "//external:javac",
        "//external:jsr305",
        "//src/main/java/org/javacomp/logging",
        "//src/main/java/org/javacomp/model/util",
        "//third_party:auto_value",
    ],
)
