java_library(
    name = "classfile",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/org/javacomp/model",
        "//src/main/java/org/javacomp/model/util",
        "//src/main/java/org/javacomp/options",
        "//third_party:auto_value",
        "//third_party:flogger",
        "//third_party:guava",
        "//third_party:javac",
        "//third_party:jsr305",
    ],
)
