java_library(
    name = "parser",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//external:guava",
        "//external:javac",
        "//external:jsr305",
        "//src/main/java/org/javacomp/logging",
        "//src/main/java/org/javacomp/model",
        "//src/main/java/org/javacomp/model/util",
        "//third_party:auto_value",
    ],
)
