java_library(
    name = "ast_scanner",
    srcs = ["AstScanner.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//external:guava",
        "//external:javac",
        "//src/main/java/org/javacomp/model:symbol_index_scope",
        "//src/main/proto:symbol_proto",
    ],
)
