java_library(
    name = "ast_scanner",
    srcs = ["AstScanner.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//external:guava",
        "//external:javac",
        "//src/main/java/org/javacomp/model",
    ],
)
