package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "completion",
    srcs = glob(["*.java"]),
    deps = [
        "//external:guava",
        "//external:javac",
        "//src/main/java/org/javacomp/model",
        "//src/main/java/org/javacomp/parser",
        "//third_party:auto_value",
    ],
)
