java_library(
    name = "typesolver",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/org/javacomp/logging",
        "//src/main/java/org/javacomp/model",
        "//src/main/java/org/javacomp/parser",
        "//third_party:auto_value",
        "//third_party:guava",
        "//third_party:javac",
        "//third_party:jsr305",
    ],
)
