package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "options",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party:auto_value",
        "//third_party:guava",
        "//third_party:jsr305",
    ],
)
