package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "options",
    srcs = glob(["*.java"]),
    deps = [
        "//external:guava",
        "//external:jsr305",
        "//third_party:auto_value",
    ],
)
